name: Release @letta-ai/vercel-ai-sdk-provider
on:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Compile
        working-directory: ./packages/letta-react
        run: npm ci && npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Test
        working-directory: .
        run: npm ci && npm test

  publish:
    needs: [compile, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
      - name: Install dependencies
        working-directory: .
        run: npm ci
      - name: Build
        working-directory: .
        run: npm run build

      - name: Publish to npm
        working-directory: .
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          if [[ ${GITHUB_REF} == *alpha* ]]; then
            npm publish --access public --tag alpha
          elif [[ ${GITHUB_REF} == *beta* ]]; then
            npm publish --access public --tag beta
          else
            npm publish --access public
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
